import React from 'react';
import { PageHeader } from '../components/PageHeader';
import { EmptyState } from '../components/EmptyState';
import { OutputFileCard } from '../components/OutputFileCard';
import { Download, ArrowRight } from 'lucide-react';
import type { PageId } from '../types';

interface CandidatePairsPageProps {
  onNavigate?: (page: PageId) => void;
}

export const CandidatePairsPage: React.FC<CandidatePairsPageProps> = ({ onNavigate }) => {
  return (
    <div className="space-y-6">
      <PageHeader
        title="Candidate Pairs Output"
        description="Inspect final candidate pairs (candidate_pairs.tsv) generated by the candidate generation / blocking stage."
        badgeText="Pipeline Stage 04"
        actions={
          <button
            disabled
            className="px-3.5 py-1.5 rounded text-xs font-medium bg-slate-100 text-slate-400 border border-slate-200 cursor-not-allowed flex items-center gap-1.5 opacity-80"
          >
            <Download className="w-3.5 h-3.5" />
            Export candidate_pairs.tsv
          </button>
        }
      />

      {/* Output Specification Card */}
      <OutputFileCard
        fileName="candidate_pairs.tsv"
        filePath="output/candidate_pairs.tsv"
        columns={['source1_entity_id', 'candidate_entity_ids']}
        description="Represents the FINAL candidate set produced by candidate generation / blocking stage, immediately before the matching model."
        rules={[
          'Every Source 1 entity in the test set must have exactly one row.',
          'candidate_entity_ids contains comma-separated candidate IDs.',
          'Candidate IDs can only originate from Source 2 (S2-*) and Source 3 (S3-*).',
          'No duplicate candidate IDs allowed within a row.',
          'Candidate list may be empty if no candidates pass blocking rules.',
          'This is the candidate set immediately before the matching model (NOT early raw blocking output).',
        ]}
      />

      {/* Visual Candidate Pair Mapping Card */}
      <div className="bg-white border border-slate-200 rounded-lg p-5 shadow-2xs">
        <h4 className="text-xs font-bold text-slate-900 mb-3 uppercase tracking-wider font-mono">
          Candidate Pair Mapping Schema Definition
        </h4>
        <div className="flex flex-col md:flex-row items-center gap-3 text-xs bg-slate-50 p-4 rounded-lg border border-slate-200">
          <div className="bg-white p-2.5 rounded border border-slate-200 font-mono text-slate-700">
            <span className="text-slate-400 block text-[10px] uppercase">source1_entity_id</span>
            <span className="font-bold text-blue-900">S1-10042</span>
          </div>
          <ArrowRight className="w-4 h-4 text-slate-400 hidden md:block" />
          <div className="bg-white p-2.5 rounded border border-slate-200 font-mono text-indigo-900 font-semibold flex-1">
            <span className="text-slate-400 block text-[10px] uppercase">candidate_entity_ids (Comma-Separated)</span>
            <span>S2-09412, S3-11849, S2-88301</span>
          </div>
        </div>
      </div>

      {/* Table Placeholder with Empty State */}
      <div className="bg-white border border-slate-200 rounded-lg p-5 shadow-2xs">
        <div className="flex items-center justify-between pb-3 border-b border-slate-200 mb-4">
          <h3 className="text-sm font-bold text-slate-900">
            candidate_pairs.tsv Data Grid
          </h3>
          <span className="text-[11px] font-mono text-slate-500 bg-slate-100 px-2 py-0.5 rounded border border-slate-200">
            Rows: 0
          </span>
        </div>

        <EmptyState
          title="No dataset loaded"
          description="Upload the challenge TSV files to begin this stage."
          actionText="Go to Datasets"
          onAction={onNavigate ? () => onNavigate('datasets') : undefined}
        />
      </div>
    </div>
  );
};
