import React, { useState } from 'react';
import { PageHeader } from '../components/PageHeader';
import { EmptyState } from '../components/EmptyState';
import { OutputFileCard } from '../components/OutputFileCard';
import { FileCheck2, Layers, FileText } from 'lucide-react';

export const ResultsPage: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'matches' | 'candidates'>('matches');

  return (
    <div>
      <PageHeader
        title="Execution Results"
        description="Inspect generated output TSV files. Maintain strict distinction between Final Matches (matching_results.tsv) and Candidate Pairs (candidate_pairs.tsv)."
        badgeText="Pipeline Stage 06"
      />

      {/* Two Clearly Separated Tabs Header */}
      <div className="flex border-b border-slate-200 mb-6 bg-slate-50 p-1 rounded-t-lg">
        <button
          onClick={() => setActiveTab('matches')}
          className={`flex items-center gap-2 px-4 py-2.5 text-xs font-bold rounded-md transition-all ${
            activeTab === 'matches'
              ? 'bg-white text-indigo-900 shadow-xs border border-slate-200'
              : 'text-slate-600 hover:text-slate-900 hover:bg-slate-100'
          }`}
        >
          <FileCheck2 className="w-4 h-4 text-indigo-600" />
          <span>TAB 1: Final Matches (matching_results.tsv)</span>
        </button>

        <button
          onClick={() => setActiveTab('candidates')}
          className={`flex items-center gap-2 px-4 py-2.5 text-xs font-bold rounded-md transition-all ${
            activeTab === 'candidates'
              ? 'bg-white text-blue-900 shadow-xs border border-slate-200'
              : 'text-slate-600 hover:text-slate-900 hover:bg-slate-100'
          }`}
        >
          <Layers className="w-4 h-4 text-blue-600" />
          <span>TAB 2: Candidate Pairs (candidate_pairs.tsv)</span>
        </button>
      </div>

      {/* TAB 1: FINAL MATCHES */}
      {activeTab === 'matches' && (
        <div className="space-y-6">
          <OutputFileCard
            fileName="matching_results.tsv"
            filePath="output/matching_results.tsv"
            columns={['source1_entity_id', 'matched_entity_ids']}
            description="Final matched entities predicted by the matching model for each test Source 1 entity."
            rules={[
              'Every Source 1 entity in the test set must have exactly one row.',
              'matched_entity_ids contains comma-separated matching entity IDs.',
              'Matches can ONLY come from Source 2 (S2-*) and Source 3 (S3-*).',
              'Source 1 IDs (S1-*) CANNOT be used as matches.',
              'Duplicate IDs are not allowed in the list.',
              'A Source 1 entity may have zero, one, or multiple matches.',
              'If there is no match, matched_entity_ids must be empty.',
              'CRITICAL: Every matched ID MUST exist in candidate_pairs.tsv for the same Source 1 entity.',
            ]}
          />

          <div className="bg-white border border-slate-200 rounded-lg p-5">
            <div className="flex items-center justify-between pb-3 border-b border-slate-200 mb-4">
              <h3 className="text-sm font-bold text-slate-900 font-mono">
                matching_results.tsv Data View
              </h3>
              <span className="text-xs font-mono text-slate-500 bg-slate-100 px-2 py-0.5 rounded border border-slate-200">
                Rows: 0 (Pipeline Not Run)
              </span>
            </div>

            <EmptyState
              icon={FileText}
              title="No matching results generated yet."
              description="The matching model will produce final resolved record IDs in output/matching_results.tsv."
              actionText="Export matching_results.tsv"
            />
          </div>
        </div>
      )}

      {/* TAB 2: CANDIDATE PAIRS */}
      {activeTab === 'candidates' && (
        <div className="space-y-6">
          <OutputFileCard
            fileName="candidate_pairs.tsv"
            filePath="output/candidate_pairs.tsv"
            columns={['source1_entity_id', 'candidate_entity_ids']}
            description="Final candidate set generated by candidate generation / blocking stage, immediately prior to entity matching."
            rules={[
              'Every Source 1 entity must have exactly one row.',
              'candidate_entity_ids contains comma-separated candidate IDs.',
              'Candidate IDs can only come from Source 2 (S2-*) and Source 3 (S3-*).',
              'No duplicate candidate IDs allowed.',
              'Candidate list may be empty if no candidates are found.',
              'This represents the FINAL candidate set produced by blocking stage.',
              'It is NOT an early/raw blocking output.',
            ]}
          />

          <div className="bg-white border border-slate-200 rounded-lg p-5">
            <div className="flex items-center justify-between pb-3 border-b border-slate-200 mb-4">
              <h3 className="text-sm font-bold text-slate-900 font-mono">
                candidate_pairs.tsv Data View
              </h3>
              <span className="text-xs font-mono text-slate-500 bg-slate-100 px-2 py-0.5 rounded border border-slate-200">
                Rows: 0 (Pipeline Not Run)
              </span>
            </div>

            <EmptyState
              icon={Layers}
              title="No candidate pairs generated yet."
              description="The candidate generation stage will output candidate pairs to output/candidate_pairs.tsv."
              actionText="Export candidate_pairs.tsv"
            />
          </div>
        </div>
      )}
    </div>
  );
};
