import type { DatasetFileSpec, ValidationRule, SubmissionCheckItem, PipelineStep } from '../types';

export const TRAINING_FILES: DatasetFileSpec[] = [
  {
    id: 'train_s1',
    name: 'train_source1.tsv',
    path: 'dataset/train/train_source1.tsv',
    source: 'Source 1',
    category: 'TRAINING',
    expectedFormat: 'TSV',
    columns: ['entity_id', 'business_name', 'business_address', 'country'],
    description: 'Deduplicated reference source dataset for training.',
    status: 'not_uploaded',
  },
  {
    id: 'train_s2',
    name: 'train_source2.tsv',
    path: 'dataset/train/train_source2.tsv',
    source: 'Source 2',
    category: 'TRAINING',
    expectedFormat: 'TSV',
    columns: ['entity_id', 'business_name', 'business_address', 'country'],
    description: 'Secondary business records dataset for training.',
    status: 'not_uploaded',
  },
  {
    id: 'train_s3',
    name: 'train_source3.tsv',
    path: 'dataset/train/train_source3.tsv',
    source: 'Source 3',
    category: 'TRAINING',
    expectedFormat: 'TSV',
    columns: ['entity_id', 'business_name', 'business_address', 'country'],
    description: 'Tertiary business records dataset for training.',
    status: 'not_uploaded',
  },
  {
    id: 'train_gt',
    name: 'train_ground_truth.tsv',
    path: 'dataset/train/train_ground_truth.tsv',
    source: 'Ground Truth',
    category: 'TRAINING',
    expectedFormat: 'TSV',
    columns: ['source1_entity_id', 'matched_entity_ids'],
    description: 'Ground truth matching labels for Source 1 entities.',
    status: 'not_uploaded',
  },
];

export const TEST_FILES: DatasetFileSpec[] = [
  {
    id: 'test_s1',
    name: 'test_source1.tsv',
    path: 'dataset/test/test_source1.tsv',
    source: 'Source 1',
    category: 'TEST',
    expectedFormat: 'TSV',
    columns: ['entity_id', 'business_name', 'business_address', 'country'],
    description: 'Deduplicated reference source dataset for test evaluation.',
    status: 'not_uploaded',
  },
  {
    id: 'test_s2',
    name: 'test_source2.tsv',
    path: 'dataset/test/test_source2.tsv',
    source: 'Source 2',
    category: 'TEST',
    expectedFormat: 'TSV',
    columns: ['entity_id', 'business_name', 'business_address', 'country'],
    description: 'Secondary business records dataset for test evaluation.',
    status: 'not_uploaded',
  },
  {
    id: 'test_s3',
    name: 'test_source3.tsv',
    path: 'dataset/test/test_source3.tsv',
    source: 'Source 3',
    category: 'TEST',
    expectedFormat: 'TSV',
    columns: ['entity_id', 'business_name', 'business_address', 'country'],
    description: 'Tertiary business records dataset for test evaluation.',
    status: 'not_uploaded',
  },
];

export const WORKFLOW_STEPS: PipelineStep[] = [
  { stepNumber: '01', title: 'Dataset', subtitle: 'Load TSV train/test datasets', status: 'Not Started' },
  { stepNumber: '02', title: 'Data Preparation', subtitle: 'Clean, normalize & detect duplicates', status: 'Not Started' },
  { stepNumber: '03', title: 'Candidate Generation', subtitle: 'Blocking & candidate set filtering', status: 'Not Started' },
  { stepNumber: '04', title: 'Candidate Pairs', subtitle: 'Final blocking output', outputArtifact: 'candidate_pairs.tsv', status: 'Not Started' },
  { stepNumber: '05', title: 'Entity Matching', subtitle: 'Matching classification model', status: 'Not Started' },
  { stepNumber: '06', title: 'Matching Results', subtitle: 'Final resolved entity pairs', outputArtifact: 'matching_results.tsv', status: 'Not Started' },
  { stepNumber: '07', title: 'Validation', subtitle: 'Integrity & schema validation', status: 'Not Started' },
  { stepNumber: '08', title: 'Packaging', subtitle: 'Distribution bundle verification', outputArtifact: 'dist/package.tar.gz', status: 'Not Started' },
];

export const VALIDATION_RULES: ValidationRule[] = [
  {
    id: 'val_files',
    title: 'Required output files exist',
    category: 'Files',
    description: 'Verifies output/matching_results.tsv and output/candidate_pairs.tsv are present.',
    expectedBehavior: 'Both TSV files present in output/ directory',
    status: 'pending',
  },
  {
    id: 'val_cols',
    title: 'Required column headers',
    category: 'Schema',
    description: 'Verifies exact column header names in output TSV files.',
    expectedBehavior: 'matching_results.tsv: source1_entity_id, matched_entity_ids | candidate_pairs.tsv: source1_entity_id, candidate_entity_ids',
    status: 'pending',
  },
  {
    id: 'val_s1_coverage',
    title: 'Every Source 1 entity included',
    category: 'Integrity',
    description: 'Ensures every Source 1 entity in the test set has exactly one row in both TSV files.',
    expectedBehavior: 'Complete 1:1 coverage of test Source 1 entity IDs',
    status: 'pending',
  },
  {
    id: 'val_single_row',
    title: 'Exactly one row per Source 1 entity',
    category: 'Integrity',
    description: 'Ensures no duplicate Source 1 entity rows exist in either output file.',
    expectedBehavior: 'Unique source1_entity_id per row',
    status: 'pending',
  },
  {
    id: 'val_no_dup_s1',
    title: 'No duplicate Source 1 IDs',
    category: 'Integrity',
    description: 'Guarantees source1_entity_id values are strictly unique in the output files.',
    expectedBehavior: '0 duplicate source1_entity_id entries',
    status: 'pending',
  },
  {
    id: 'val_valid_s2_s3',
    title: 'Valid Source 2 / Source 3 entity IDs',
    category: 'Integrity',
    description: 'Verifies matching and candidate IDs strictly originate from Source 2 (S2-*) and Source 3 (S3-*).',
    expectedBehavior: 'All matched & candidate IDs start with S2- or S3-',
    status: 'pending',
  },
  {
    id: 'val_no_self_match',
    title: 'No Source 1 self-matching',
    category: 'Constraints',
    description: 'Verifies that Source 1 IDs (S1-*) are never included as matched or candidate entity IDs.',
    expectedBehavior: '0 Source 1 IDs in matched_entity_ids or candidate_entity_ids',
    status: 'pending',
  },
  {
    id: 'val_no_dup_list_ids',
    title: 'No duplicate IDs in matched/candidate lists',
    category: 'Constraints',
    description: 'Ensures comma-separated lists do not contain repeated entity IDs for the same row.',
    expectedBehavior: 'Unique entity IDs within each comma-separated string',
    status: 'pending',
  },
  {
    id: 'val_subset_rule',
    title: 'Final matches are a subset of candidates',
    category: 'Constraints',
    description: 'CRITICAL RULE: Every entity ID in matching_results.tsv MUST appear in candidate_pairs.tsv for the same Source 1 entity (FINAL MATCHES ⊆ FINAL CANDIDATES).',
    expectedBehavior: 'matched_entity_ids ⊆ candidate_entity_ids per Source 1 entity',
    status: 'pending',
  },
  {
    id: 'val_tsv_format',
    title: 'Tab-Separated Value (TSV) format',
    category: 'Format',
    description: 'Ensures output files are strictly tab-separated plain text files with no CSV or JSON formatting.',
    expectedBehavior: 'Tab-character delimited TSV text encoding',
    status: 'pending',
  },
];

export const SUBMISSION_CHECKLIST: SubmissionCheckItem[] = [
  { id: 'rel_1', label: 'Core modular ML package structured in src/business_entity_resolution/', fileOrFolder: 'src/business_entity_resolution/', required: true, completed: true },
  { id: 'rel_2', label: 'CLI entry point scripts (train.py, evaluate.py, predict.py) implemented', fileOrFolder: 'scripts/', required: true, completed: true },
  { id: 'rel_3', label: 'Self-contained synthetic demo dataset & runner ready', fileOrFolder: 'examples/run_demo.py', required: true, completed: true },
  { id: 'rel_4', label: 'Unit test suite passing (normalization, blocking, features, pipeline)', fileOrFolder: 'tests/', required: true, completed: true },
  { id: 'rel_5', label: 'Standard Python packaging files configured (pyproject.toml, requirements.txt)', fileOrFolder: 'pyproject.toml', required: true, completed: true },
  { id: 'rel_6', label: 'Architecture and methodology documentation authored', fileOrFolder: 'docs/', required: true, completed: true },
  { id: 'rel_7', label: 'Integrity validation engine ready (10/10 data constraint checks)', fileOrFolder: 'src/business_entity_resolution/evaluation.py', required: true, completed: true },
  { id: 'rel_8', label: 'No hardcoded credentials, API keys, or local machine paths', fileOrFolder: 'Repository-wide scan', required: true, completed: true },
  { id: 'rel_9', label: 'Comprehensive production-quality README with system diagrams', fileOrFolder: 'README.md', required: true, completed: true },
  { id: 'rel_10', label: 'Memory-safe streaming pipeline with disk-backed SQLite indexing', fileOrFolder: 'src/business_entity_resolution/pipeline.py', required: true, completed: true },
];
